//! Source connector registry for preserved, backend-owned discovery snapshots.
//!
//! These connectors deliberately do not contain provider clients. They consume
//! bounded source responses already written into the case artifact store. This
//! keeps discovery attributable and makes connected-but-empty results honest:
//! no connector claims live or organization-wide visibility it did not have.

mod artifact;
mod parser;

pub use artifact::{
    LIVE_PROVIDER_ARTIFACT_METADATA_KEY, LIVE_PROVIDER_ARTIFACT_SET_SCHEMA,
    LiveProviderArtifactPage, LiveProviderArtifactSet, MAX_LIVE_PROVIDER_PAGES, MAX_SNAPSHOT_BYTES,
    SNAPSHOT_ARTIFACT_METADATA_KEY, SNAPSHOT_REFERENCE_SCHEMA, SnapshotArtifactReference,
};

use crate::discovery::{
    ConnectorDiscovery, DiscoveredRelation, DiscoveryAssetRef, DiscoveryConnector, DiscoveryError,
};
use crate::domain::{AssetKind, DataSource, RelationKind, SourceKind};
use artifact::{
    ingest_provider_response, ingest_selected_source, inspect_snapshot_reference,
    prepare_artifact_root, read_snapshot_reference, read_source_snapshot,
};
use chrono::{DateTime, Utc};
use parser::{ParserProfile, parse_snapshot};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

pub const SNAPSHOT_CONNECTOR_VERSION: &str = "1.0.0";

/// Checks whether a preserved passive-source snapshot can be used before a
/// scan record is created.
///
/// This is a pure, bounded read: it never creates the artifact root, changes
/// permissions, writes metadata, parses the snapshot, or contacts its source.
/// The same schema, source/profile binding, normalized path, symlink, regular
/// file, size, and optional SHA-256 checks are repeated by the connector at
/// execution time as a TOCTOU defense.
pub fn preflight_snapshot_artifact(
    artifact_root: impl AsRef<Path>,
    source_kind: &SourceKind,
    reference: &SnapshotArtifactReference,
) -> Result<(), DiscoveryError> {
    let artifact_root = prepare_artifact_root(artifact_root)?;
    let descriptor = definition(source_kind);
    inspect_snapshot_reference(&artifact_root, reference, descriptor.parser_profiles)?;
    Ok(())
}

#[derive(Debug, Clone)]
pub struct ConnectorDescriptor {
    pub connector_id: &'static str,
    pub source_kind: SourceKind,
    pub parser_profiles: &'static [&'static str],
    pub live_discovery: bool,
}

/// Registry rooted at the case's connector artifact directory.
///
/// Construction canonicalizes a real, non-symlink directory. Every returned
/// connector retains that exact root and cannot be redirected by source data.
#[derive(Debug, Clone)]
pub struct SnapshotConnectorRegistry {
    artifact_root: PathBuf,
}

impl SnapshotConnectorRegistry {
    pub fn new(artifact_root: impl AsRef<Path>) -> Result<Self, DiscoveryError> {
        Ok(Self {
            artifact_root: prepare_artifact_root(artifact_root)?,
        })
    }

    /// Selects one connector by exact `SourceKind`. There is no generic fallback
    /// that could interpret one source's bytes as another provider.
    pub fn connector_for(&self, source_kind: &SourceKind) -> SnapshotConnector {
        let definition = definition(source_kind);
        SnapshotConnector {
            artifact_root: self.artifact_root.clone(),
            source_kind: definition.source_kind,
            connector_id: definition.connector_id,
            parser_profiles: definition.parser_profiles,
        }
    }

    pub fn descriptors(&self) -> Vec<ConnectorDescriptor> {
        all_source_kinds().iter().map(definition).collect()
    }

    pub fn artifact_root(&self) -> &Path {
        &self.artifact_root
    }

    /// Copies a file explicitly selected by the user into the connector
    /// artifact store. The destination is always generated by the backend;
    /// callers cannot supply a relative path or overwrite an artifact.
    pub fn ingest_selected_snapshot(
        &self,
        source_kind: &SourceKind,
        selected_source_path: impl AsRef<Path>,
        profile: &str,
        observed_at: DateTime<Utc>,
    ) -> Result<SnapshotArtifactReference, DiscoveryError> {
        let definition = definition(source_kind);
        ingest_selected_source(
            &self.artifact_root,
            selected_source_path.as_ref(),
            profile,
            observed_at,
            definition.parser_profiles,
        )
    }

    /// Persists one exact provider response before any inventory parser sees
    /// it. The returned reference contains no provider credential or cursor.
    pub fn ingest_provider_response(
        &self,
        source_kind: &SourceKind,
        bytes: &[u8],
        profile: &str,
        observed_at: DateTime<Utc>,
    ) -> Result<SnapshotArtifactReference, DiscoveryError> {
        let definition = definition(source_kind);
        ingest_provider_response(
            &self.artifact_root,
            bytes,
            profile,
            observed_at,
            definition.parser_profiles,
        )
    }
}

#[derive(Debug, Clone)]
pub struct SnapshotConnector {
    artifact_root: PathBuf,
    source_kind: SourceKind,
    connector_id: &'static str,
    parser_profiles: &'static [&'static str],
}

impl SnapshotConnector {
    pub fn parser_profiles(&self) -> &'static [&'static str] {
        self.parser_profiles
    }
}

impl DiscoveryConnector for SnapshotConnector {
    fn connector_id(&self) -> &str {
        self.connector_id
    }

    fn connector_version(&self) -> &str {
        SNAPSHOT_CONNECTOR_VERSION
    }

    fn source_kind(&self) -> SourceKind {
        self.source_kind.clone()
    }

    fn discover(&self, source: &DataSource) -> Result<ConnectorDiscovery, DiscoveryError> {
        if source.kind != self.source_kind {
            return Err(DiscoveryError::SourceKindMismatch {
                source_id: source.id.clone(),
            });
        }
        let mut discovery = if let Some(value) =
            source.metadata.get(LIVE_PROVIDER_ARTIFACT_METADATA_KEY)
        {
            let set: LiveProviderArtifactSet =
                serde_json::from_value(value.clone()).map_err(|error| {
                    DiscoveryError::Connector(format!(
                        "source {} has an invalid live provider artifact set: {error}",
                        source.id
                    ))
                })?;
            validate_live_provider_set(&set, self.parser_profiles)?;
            let profile = ParserProfile::from_id(&set.profile).ok_or_else(|| {
                DiscoveryError::Connector(format!(
                    "connector {} has no implementation for its live provider parser profile",
                    self.connector_id
                ))
            })?;
            let mut combined = ConnectorDiscovery {
                observed_at: set.observed_at,
                assets: Vec::new(),
                relations: Vec::new(),
                notices: Vec::new(),
            };
            let mut successful_pages = 0_usize;
            let mut observation_keys = BTreeSet::new();
            let mut relation_keys = BTreeSet::new();
            for page in &set.pages {
                if !(200..300).contains(&page.http_status) || !page.parser_eligible {
                    combined.notices.push(format!(
                        "preserved provider response page {} for {} returned HTTP {} or failed its minimal response contract; it was not interpreted as inventory",
                        page.sequence, page.operation, page.http_status,
                    ));
                    continue;
                }
                let snapshot = read_snapshot_reference(
                    &self.artifact_root,
                    page.artifact.clone(),
                    self.parser_profiles,
                )?;
                // The durable manifest and the page reference must agree on
                // the parser profile before bytes enter a parser.
                if snapshot.reference.profile != set.profile {
                    return Err(DiscoveryError::Connector(
                        "live provider artifact profiles do not agree".into(),
                    ));
                }
                let page_discovery = parse_snapshot(
                    profile,
                    &source.kind,
                    &snapshot.bytes,
                    &snapshot.reference.artifact_id,
                    set.observed_at,
                )?;
                successful_pages += 1;
                combined.assets.extend(
                    page_discovery
                        .assets
                        .into_iter()
                        .filter(|asset| observation_keys.insert(asset.observation_key.clone())),
                );
                combined
                    .relations
                    .extend(page_discovery.relations.into_iter().filter(|relation| {
                        let key = serde_json::to_string(relation).unwrap_or_default();
                        !key.is_empty() && relation_keys.insert(key)
                    }));
                combined.notices.extend(page_discovery.notices);
            }
            if profile == ParserProfile::GcpResourceManagerProjects {
                finalize_gcp_hierarchy(&mut combined)?;
            }
            if successful_pages == 0 {
                return Err(DiscoveryError::Connector(
                    "live provider capture contains no successful response page to parse".into(),
                ));
            }
            combined.notices.insert(
                0,
                format!(
                    "{} parsed {} successful page(s) only after their exact provider responses were durably preserved and SHA-256 verified",
                    self.connector_id, successful_pages
                ),
            );
            if !set.complete {
                combined.notices.push(
                    "the provider capture is partial; retained observations do not establish complete source coverage"
                        .into(),
                );
            }
            combined
        } else {
            let snapshot = read_source_snapshot(&self.artifact_root, source, self.parser_profiles)?;
            let profile = ParserProfile::from_id(&snapshot.reference.profile).ok_or_else(|| {
                DiscoveryError::Connector(format!(
                    "connector {} has no implementation for its selected bounded parser profile",
                    self.connector_id
                ))
            })?;
            let mut discovery = parse_snapshot(
                profile,
                &source.kind,
                &snapshot.bytes,
                &snapshot.reference.artifact_id,
                snapshot.reference.observed_at,
            )?;
            discovery.notices.insert(
                0,
                format!(
                    "{} consumes preserved provider output from evidence artifact {}; it did not perform live discovery or make network requests",
                    self.connector_id, snapshot.reference.artifact_id
                ),
            );
            discovery
        };
        discovery.notices.push(
            "all observed assets remain candidates; this connector did not confirm ownership or grant scan scope"
                .into(),
        );
        Ok(discovery)
    }
}

/// Cloud Resource Manager list operations return only direct children. Fold
/// the fully captured, exact folder tree into an organization-to-project
/// containment edge so the existing execution boundary can authorize only a
/// project with one proven path to the verified organization.
fn finalize_gcp_hierarchy(discovery: &mut ConnectorDiscovery) -> Result<(), DiscoveryError> {
    #[derive(Clone)]
    struct Identity {
        kind: AssetKind,
        provider: Option<String>,
        namespace: String,
        value: String,
    }

    let identities = discovery
        .assets
        .iter()
        .map(|asset| {
            (
                asset.observation_key.clone(),
                Identity {
                    kind: asset.kind.clone(),
                    provider: asset.provider.clone(),
                    namespace: asset.stable_identifier.namespace.clone(),
                    value: asset.stable_identifier.value.clone(),
                },
            )
        })
        .collect::<std::collections::BTreeMap<_, _>>();
    let mut parents = std::collections::BTreeMap::<String, Vec<(String, Vec<String>)>>::new();
    for relation in &discovery.relations {
        let (DiscoveryAssetRef::Observation(from), DiscoveryAssetRef::Observation(to)) =
            (&relation.from, &relation.to)
        else {
            continue;
        };
        if relation.kind == RelationKind::Contains {
            parents
                .entry(to.clone())
                .or_default()
                .push((from.clone(), relation.evidence_ids.clone()));
        }
    }

    let projects = identities
        .iter()
        .filter_map(|(key, identity)| {
            (identity.kind == AssetKind::Project
                && identity.provider.as_deref() == Some("gcp")
                && identity.namespace == "gcp_project_id")
                .then_some(key.clone())
        })
        .collect::<Vec<_>>();
    let mut derived = Vec::new();
    let mut expected_organization = None::<String>;
    for project in projects {
        let mut current = project.clone();
        let mut visited = BTreeSet::new();
        let mut evidence = BTreeSet::new();
        loop {
            if !visited.insert(current.clone()) || visited.len() > 64 {
                return Err(DiscoveryError::Connector(
                    "Google project hierarchy contains a cycle or exceeds its depth bound".into(),
                ));
            }
            let Some(edges) = parents.get(&current) else {
                return Err(DiscoveryError::Connector(
                    "Google project has no complete path to one organization".into(),
                ));
            };
            if edges.len() != 1 {
                return Err(DiscoveryError::Connector(
                    "Google project hierarchy has an ambiguous parent".into(),
                ));
            }
            let (parent, edge_evidence) = &edges[0];
            evidence.extend(edge_evidence.iter().cloned());
            let identity = identities.get(parent).ok_or_else(|| {
                DiscoveryError::Connector(
                    "Google project hierarchy references an unknown parent".into(),
                )
            })?;
            if identity.provider.as_deref() != Some("gcp") {
                return Err(DiscoveryError::Connector(
                    "Google project hierarchy crosses a provider boundary".into(),
                ));
            }
            if identity.kind == AssetKind::CloudOrganization
                && identity.namespace == "gcp_organization_id"
                && identity.value.bytes().all(|byte| byte.is_ascii_digit())
            {
                if expected_organization
                    .as_ref()
                    .is_some_and(|expected| expected != &identity.value)
                {
                    return Err(DiscoveryError::Connector(
                        "Google project capture resolves to multiple organizations".into(),
                    ));
                }
                expected_organization = Some(identity.value.clone());
                if parent != &current && current != project {
                    derived.push(DiscoveredRelation {
                        from: DiscoveryAssetRef::Observation(parent.clone()),
                        to: DiscoveryAssetRef::Observation(project.clone()),
                        kind: RelationKind::Contains,
                        evidence_ids: evidence.into_iter().collect(),
                    });
                }
                break;
            }
            if identity.kind != AssetKind::Other
                || identity.namespace != "gcp_folder_id"
                || identity.value.is_empty()
                || !identity.value.bytes().all(|byte| byte.is_ascii_digit())
            {
                return Err(DiscoveryError::Connector(
                    "Google project hierarchy contains an invalid folder parent".into(),
                ));
            }
            current = parent.clone();
        }
    }
    discovery.relations.extend(derived);
    Ok(())
}

fn definition(kind: &SourceKind) -> ConnectorDescriptor {
    match kind {
        SourceKind::AwsOrganization => ConnectorDescriptor {
            connector_id: "aws-organization-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &[
                "cloudquery",
                "steampipe",
                "prowler",
                "aws-organizations-list-accounts",
            ],
            live_discovery: true,
        },
        SourceKind::AzureTenant => ConnectorDescriptor {
            connector_id: "azure-tenant-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &[
                "cloudquery",
                "steampipe",
                "prowler",
                "azure-resource-manager-resources",
            ],
            live_discovery: true,
        },
        SourceKind::GcpOrganization => ConnectorDescriptor {
            connector_id: "gcp-organization-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &[
                "cloudquery",
                "steampipe",
                "prowler",
                "gcp-resource-manager-projects",
            ],
            live_discovery: true,
        },
        SourceKind::Microsoft365Tenant => ConnectorDescriptor {
            connector_id: "microsoft365-tenant-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &[
                "scubagear",
                "maester",
                "microsoft-graph-directory-inventory",
            ],
            live_discovery: true,
        },
        SourceKind::Dns => ConnectorDescriptor {
            connector_id: "dns-response-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["dns-response"],
            live_discovery: false,
        },
        SourceKind::CertificateTransparency => ConnectorDescriptor {
            connector_id: "certificate-transparency-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["certificate-transparency-response"],
            live_discovery: false,
        },
        SourceKind::Billing => ConnectorDescriptor {
            connector_id: "billing-export-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["billing-export"],
            live_discovery: false,
        },
        SourceKind::GitRepository => ConnectorDescriptor {
            connector_id: "git-repository-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["git-manifest"],
            live_discovery: false,
        },
        SourceKind::TerraformState => ConnectorDescriptor {
            connector_id: "terraform-state-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["terraform-state"],
            live_discovery: false,
        },
        SourceKind::KubernetesCluster => ConnectorDescriptor {
            connector_id: "kubernetes-cluster-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["kubernetes-manifest"],
            live_discovery: false,
        },
        SourceKind::ContainerRegistry => ConnectorDescriptor {
            connector_id: "container-registry-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["container-registry-manifest"],
            live_discovery: false,
        },
        SourceKind::FileSystem => ConnectorDescriptor {
            connector_id: "filesystem-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["filesystem-manifest"],
            live_discovery: false,
        },
        SourceKind::UserDeclared => ConnectorDescriptor {
            connector_id: "user-declared-snapshot-v1",
            source_kind: kind.clone(),
            parser_profiles: &["user-declared-manifest"],
            live_discovery: false,
        },
    }
}

fn validate_live_provider_set(
    set: &LiveProviderArtifactSet,
    allowed_profiles: &[&str],
) -> Result<(), DiscoveryError> {
    if set.schema_version != LIVE_PROVIDER_ARTIFACT_SET_SCHEMA
        || set.capture_id.is_empty()
        || set.capture_id.len() > 128
        || !set
            .capture_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        || set.operation.is_empty()
        || set.operation.len() > 128
        || set.operation.chars().any(char::is_control)
        || !allowed_profiles.contains(&set.profile.as_str())
        || set.pages.is_empty()
        || set.pages.len() > MAX_LIVE_PROVIDER_PAGES
    {
        return Err(DiscoveryError::Connector(
            "live provider artifact set is malformed or outside limits".into(),
        ));
    }
    for (index, page) in set.pages.iter().enumerate() {
        if usize::from(page.sequence) != index + 1
            || page.operation.is_empty()
            || page.operation.len() > 128
            || page.operation.chars().any(char::is_control)
            || !(100..=599).contains(&page.http_status)
            || (page.parser_eligible && !(200..300).contains(&page.http_status))
            || page.artifact.profile != set.profile
            || page.artifact.observed_at != set.observed_at
        {
            return Err(DiscoveryError::Connector(
                "live provider artifact page manifest is malformed".into(),
            ));
        }
    }
    Ok(())
}

fn all_source_kinds() -> [SourceKind; 13] {
    [
        SourceKind::AwsOrganization,
        SourceKind::AzureTenant,
        SourceKind::GcpOrganization,
        SourceKind::Microsoft365Tenant,
        SourceKind::Dns,
        SourceKind::CertificateTransparency,
        SourceKind::Billing,
        SourceKind::GitRepository,
        SourceKind::TerraformState,
        SourceKind::KubernetesCluster,
        SourceKind::ContainerRegistry,
        SourceKind::FileSystem,
        SourceKind::UserDeclared,
    ]
}
